name: ragcv
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.*
  - scipy=1.12.*
  - faiss-cpu>=1.13.0
  - pytorch=2.3.*
  - torchvision
  - torchaudio
  - llvm-openmp=17.*
  - pip
  - pip:
      - -r requirements.txt